version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:5173"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: ["sh", "-c", "npm install && npm run dev"]